
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: brandskyddbot-app
    restart: unless-stopped
    ports:
      - "8501:8501"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
    volumes:
      - ./data:/data  # valfritt för att spara index/temporära filer
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/brandskydd"]
      interval: 30s
      timeout: 5s
      retries: 5

  nginx:
    image: nginx:1.25-alpine
    container_name: brandskyddbot-nginx
    depends_on:
      - app
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
